// <auto-generated />
using System;
using System.Collections.Generic;
using FoodApp.PrimerAvance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodApp.PrimerAvance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251113002440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.DetallePedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<List<string>>("OpcionesPersonalizables")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoordenadasGPS")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<bool>("Predeterminada")
                        .HasColumnType("boolean");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DatosEncriptados")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoTarjeta")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("DireccionEntregaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Propina")
                        .HasColumnType("numeric");

                    b.Property<int>("TiempoEstimado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DireccionEntregaId");

                    b.HasIndex("PagoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<List<string>>("OpcionesDieteticas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestauranteId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("RestauranteId1");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Calificacion")
                        .HasColumnType("double precision");

                    b.Property<string>("DireccionTexto")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text");

                    b.Property<string>("Ruc")
                        .HasColumnType("text");

                    b.Property<int>("TiempoEntrega")
                        .HasColumnType("integer");

                    b.Property<string>("UbicacionGPS")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f354ed19-48c6-4de0-a081-f39c6220eaaf"),
                            Calificacion = 4.5,
                            Estado = 0,
                            FechaCreacion = new DateTime(2025, 11, 13, 0, 24, 38, 984, DateTimeKind.Utc).AddTicks(9334),
                            NombreComercial = "Pizzeria Italiana",
                            TiempoEntrega = 30
                        },
                        new
                        {
                            Id = new Guid("3708cfb0-1263-41ec-8e4f-58bec7d860e1"),
                            Calificacion = 4.7999999999999998,
                            Estado = 0,
                            FechaCreacion = new DateTime(2025, 11, 13, 0, 24, 38, 984, DateTimeKind.Utc).AddTicks(9347),
                            NombreComercial = "Sushi Express",
                            TiempoEntrega = 25
                        });
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Valoracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalificacionPedido")
                        .HasColumnType("integer");

                    b.Property<int>("CalificacionRestaurante")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaValoracion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Cliente", b =>
                {
                    b.HasBaseType("FoodApp.PrimerAvance.Models.Usuario");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Repartidor", b =>
                {
                    b.HasBaseType("FoodApp.PrimerAvance.Models.Usuario");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Licencia")
                        .HasColumnType("text");

                    b.Property<string>("Vehiculo")
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Repartidor");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.DetallePedido", b =>
                {
                    b.HasOne("FoodApp.PrimerAvance.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodApp.PrimerAvance.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Direccion", b =>
                {
                    b.HasOne("FoodApp.PrimerAvance.Models.Cliente", null)
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Pedido", b =>
                {
                    b.HasOne("FoodApp.PrimerAvance.Models.Cliente", null)
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("FoodApp.PrimerAvance.Models.Direccion", "DireccionEntrega")
                        .WithMany()
                        .HasForeignKey("DireccionEntregaId");

                    b.HasOne("FoodApp.PrimerAvance.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId");

                    b.Navigation("DireccionEntrega");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Producto", b =>
                {
                    b.HasOne("FoodApp.PrimerAvance.Models.Restaurante", null)
                        .WithMany("Menu")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodApp.PrimerAvance.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Restaurante", b =>
                {
                    b.Navigation("Menu");
                });

            modelBuilder.Entity("FoodApp.PrimerAvance.Models.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("HistorialPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
